-   hosts: all
    become: true
    tasks:
    - name: ensure repository key is installed
      apt_key:
        id: "58118E89F3A912897C070ADBF76221572C52609D"
        keyserver: "hkp://p80.pool.sks-keyservers.net:80"
        state: present

    - name: ensure docker registry is available
      # For Ubuntu 14.04 LTS, use this repository:
      apt_repository: 
        repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

    - name: ensure docker and dependencies are installed
      apt: 
        name=docker-engine 
        update_cache=yes

    - service: 
        name=docker 
        state=restarted
    
    #- name: run a docker container using a project directory
    - docker_service:
        project_src: compose
        state: present
      register: output