-   hosts: all
    become: true
    tasks:
    - name: asegurarse que la llave del repositorio está instalada
      apt_key:
        id: "58118E89F3A912897C070ADBF76221572C52609D"
        keyserver: "hkp://p80.pool.sks-keyservers.net:80"
        state: present

    - name: asegurarse que el repositorio de docker esté disponible
      # Para Ubuntu 14.04 LTS, usar este repositorio:
      apt_repository: 
        repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' 
        state=present

    - name: asegurarse que docker y sus dependencias estén instalados
      apt: 
        name=docker-engine 
        update_cache=yes

    - service: 
        name=docker 
        state=restarted
    
    #- name: ejecutar conenedores docker usando el directorio de un proyecto
    - docker_service:
        project_src: compose
        state: present
      register: output